name: grocery_scanner_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  gap: ^3.0.1
  get_it: ^7.6.7
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  loading_animation_widget: ^1.2.1
  logger: ^2.4.0
  meta: ^1.10.0
  path_provider: ^2.1.3
  reactive_forms: ^17.0.1
  skeletonizer: ^1.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
